---
# tasks file for nginx-proxy
- name: "Install Nginx"
  import_tasks: install.yml
  tags:
    - packages

- name: "Create .well-known"
  file:
    path: "/var/www/{{ _vhost['name'] }}/.well-known"
    state: directory
    mode: "0755"
  loop: "{{ nginx_virtual_hosts }}"
  loop_control:
    loop_var: _vhost
  tags:
    - nginx

- name: "Remove vhost configs"
  file:
    path: /etc/nginx/conf.d/{{ _vhost['name'] }}.conf
    state: absent
  loop: "{{ nginx_virtual_hosts | selectattr('state', 'defined') | selectattr('state', 'equalto', 'absent') }}"
  loop_control:
    loop_var: _vhost
  tags:
    - nginx
    - nginx_config

- name: "Upload vhost configs"
  include_tasks: "{{ _vhost['type'] }}.yml"
  loop: "{{ nginx_virtual_hosts | rejectattr('state', 'undefined') | rejectattr('state', 'equalto', 'absent') | union(nginx_virtual_hosts | selectattr('state', 'undefined')) }}"
  loop_control:
    loop_var: _vhost
  tags:
    - nginx
    - nginx_config

- name: "Nginx service"
  service:
    name: nginx.service
    enabled: True
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - nginx

