---
- name: Install Nginx on RedHat
  yum:
    name: nginx
    state: "{{ packages_state | default('present') }}"

- name: Install Certbot
  yum:
    name:
      - certbot
      - python3-certbot-nginx
    state: "{{ packages_state | default('present') }}"
  when: nginx.letsencrypt | default(True)
